// Extracts every ```csharp block from readme.md (and combinators.md) into a
// compilable C# file per section, so the docs stay the single source of truth
// for samples. The snippet conventions are described in snippets.mjs; here,
// statements become the body of the section's Run() method, declarations go
// to namespace level, and each `// => expected` is checked at runtime: the
// value's rendering is compared with `expected` and mismatches are reported.
// A checked statement is also compiled verbatim (in dead code) so that a
// snippet like `1 + 1; // => 2`, which is not a valid C# statement, fails the build.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { readSections, splitSection } from './snippets.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const outDir = path.join(here, 'Generated')

const pascal = s => s.replace(/[^A-Za-z0-9]+/g, ' ').trim().split(' ')
  .map(w => w[0].toUpperCase() + w.slice(1)).join('')

fs.rmSync(outDir, { recursive: true, force: true })
fs.mkdirSync(outDir, { recursive: true })

const registry = []
for (const s of readSections()) {
  if (s.blocks.length === 0) continue
  const rel = path.relative(outDir, s.filePath).replaceAll('\\', '/')
  const check = ({ text, variable, expected, line }) => {
    const lit = JSON.stringify(expected)
    const at = `${line}, ${JSON.stringify(s.file)}`
    return variable
      ? `${text}; Jargon.Check.That(${variable}, ${lit}, ${at});`
      : `if (false) { ${text.trim()}; } Jargon.Check.That(${text.trim()}, ${lit}, ${at});`
  }
  const { usings, stmts, decls } = splitSection(s, { check, lineFile: rel })
  const ns = s.prefix + pascal(s.title)
  const title = s.prefix ? `${s.prefix}: ${s.title}` : s.title
  registry.push({ ns, title })
  const file = [
    '// <auto-generated/> by extract.mjs from readme.md — do not edit.',
    '#nullable enable',
    '#pragma warning disable CS0162, CS1998, CS8321, CS0168, CS0219, CS8618, CS8602, CS8604',
    `namespace Jargon.Sections.${ns}Section;`,
    ...usings,
    '#line default',
    'public static class Section',
    '{',
    `    public const string Title = ${JSON.stringify(title)};`,
    '    public static async Task Run()',
    '    {',
    ...stmts,
    '#line default',
    '    }',
    '}',
    ...decls,
    ''
  ].join('\n')
  fs.writeFileSync(path.join(outDir, `${ns}.cs`), file)
}

fs.writeFileSync(path.join(outDir, '_Registry.cs'), [
  '// <auto-generated/>',
  'namespace Jargon;',
  'public static class Registry',
  '{',
  '    public static readonly (string Title, Func<Task> Run)[] Sections =',
  '    [',
  ...registry.map(r => `        (${JSON.stringify(r.title)}, Jargon.Sections.${r.ns}Section.Section.Run),`),
  '    ];',
  '}',
  ''
].join('\n'))

console.log(`Extracted ${registry.length} sections with C# samples.`)
